---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
app_download_file: cmctl
app_download_link: https://github.com/cert-manager/cert-manager/releases/download/v${version}/cmctl-${os}-${arch}.tar.gz
app_download_type: file
app_git_repo: https://github.com/cert-manager/cert-manager
app_name: cmctl
app_strip_component: 0
git_remote: https://github.com/kc-workspace/asdf-cmctl.git
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-cmctl
plugin_org: kc-workspace
setting_os_mapper_darwin: darwin
setting_os_mapper_linux: linux
settings_os_mapper_enabled: false
