---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-4-gf6a01af
_src_path: .
app_description: a command line tool that can help you manage cert-manager and its
    resources inside your cluster.
app_name: cmctl
app_repo: https://github.com/cert-manager/cert-manager
app_version_prefix: v
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86_64: amd64
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
download_checksum_enabled: false
download_link: https://github.com/cert-manager/cert-manager/releases/download/v{version}/cmctl-{os}-{arch}.tar.gz
download_location: cmctl
download_strip: 0
download_type: archive-file
install_type: single-file
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-cmctl
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-cmctl
test_cmd_args: ''
